### PR TITLE
Redirect to the current node after publish instead of parent

### PR DESCRIPTION
**Pull request by iherak**

### CODE REVIEW

**Comment by emodric** [comment]
@peterkeung @wizhippo @thiagocamposviana @SalvatorePollaci @pkamps We're discussing making this option a default.

How do you feel about it?

I apologize in advance if I tagged anyone not using Netgen Admin UI any more :)

**Comment by wizhippo** [comment]
Redirecting to the published content seems more intuitive to me.

**Comment by SalvatorePollaci** [comment]
I agree with @wizhippo. After publishing a content, I normally have a quick glance at the content's preview panel to make sure it corresponds to what I've just published.

**Comment by pkamps** [comment]
Isn't there a setting to control the behaviour?

**Comment by emodric** [comment]
It is, it's in the PR :) I'm asking if it should be the default. You can ofcourse configure it back if you don't like it.

**Comment by peterkeung** [comment]
+1

We frequently use that setting.

**Comment by pkamps** [comment]
Doh, didn't look at the changed files.
I like it.

**Comment by emodric** [comment]
Thanks for comments everyone :)

**Pull request merged**
